version: "3.7"

services:

  school--service-db:
    image: postgres
    container_name: school--service-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: school
    volumes:
      - pgschooldata:/data/postgres

volumes:
  pgschooldata: